### ISSUE TITLE
Markdown - ordered lists don't parse properly

### ISSUE THREAD

**Issue by evilnick** [ubuntu/tutorial-deployment#1]
Hi, thanks for your work on enabling markdown for codelabs. there are a few issues with the parsing though. I'm not sure if you would prefer I add them here or on the google tools site?
Here is the first one though:

Ordered lists do not parse properly. 

For example:

```
This is a list:

 1. List item one

 2. List item two
```

Should be parsed as something like:

```
<ol>
<li>List item one</li>
<li>List item two</li>
</ol>
```

Instead it is parsed as:

```
<ol start="1">
<li>p</li>
<li>p</li>
</ol>
```

**Comment by didrocks** [comment]
Thanks for trying it this project! I didn't communicate about it yet as it's not fully finish.

I started yesterday to create a first real-world template and faced exactly those issues: https://github.com/didrocks/tutorials.ubuntu.com/blob/guidelines-example/examples/guidelines-snap-tutorials.md (see the "pbs" section at the end). Indeed, I discovered that way that most of the code from the md parser claat google project isn't reentrant.

I'm currently working on fixing those before upstreaming to google. This will required quite some refactoring on the code. I'll keep you posted here once done so that you can play and find the bugs from this importer I didn't find out myself :)

**Comment by didrocks** [comment]
Those are all fixed by the new parser by now.
